apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - image: fullstackappdb
      imagePullPolicy: Never
      name: postgres
      resources:
        limits:
          memory: 512 Mi
          cpu: "1"
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
